import { NextRequest, NextResponse } from 'next/server';
import { getAdminSupabase } from '@/lib/server/supabase-admin';

const allowed: Record<string, string[]> = { pending: ['accepted','rejected'], pending_payment: ['accepted','rejected'], paid: ['accepted','rejected'], accepted: ['dispatched','rejected'], dispatched: [], rejected: [], confirmed: ['dispatched','rejected'], processing: ['dispatched','rejected'], cancelled: [] };
async function administrator(request: NextRequest) { const token = request.headers.get('authorization')?.replace('Bearer ', ''); if (!token) return null; const db = getAdminSupabase(); const { data: user } = await db.auth.getUser(token); if (!user.user) return null; const { data: admin } = await db.from('admin_users').select('user_id').eq('user_id', user.user.id).eq('is_active', true).maybeSingle(); return admin ? { db, userId: user.user.id } : null; }
async function sendDispatchEmail(recipient: string, message: string) { if (!process.env.RESEND_API_KEY || !process.env.ORDER_FROM_EMAIL) return { status: 'not_configured', error: 'Email provider not configured' }; const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: process.env.ORDER_FROM_EMAIL, to: [recipient], subject: 'Your ChupaHub order is dispatched', text: message }) }); const payload = await response.json().catch(() => ({})); return response.ok ? { status: 'sent', reference: payload.id as string } : { status: 'failed', error: payload.message || 'Email provider rejected the notification' }; }

export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const admin = await administrator(request); if (!admin) return NextResponse.json({ error: 'Administrator access required.' }, { status: 403 });
  const { id } = await params; const body = await request.json() as { status: string; note?: string; riderName?: string; riderPhone?: string; deliveryNote?: string; trackingUrl?: string };
  const { data: order } = await admin.db.from('orders').select('id,status,order_number,total,customer_email,customer_phone').eq('id', id).maybeSingle(); if (!order) return NextResponse.json({ error: 'Order not found.' }, { status: 404 });
  if (!allowed[order.status]?.includes(body.status)) return NextResponse.json({ error: `Cannot move a ${order.status} order to ${body.status}.` }, { status: 400 });
  const update: Record<string, unknown> = { status: body.status }; if (body.status === 'dispatched') Object.assign(update, { dispatched_at: new Date().toISOString(), rider_name: body.riderName || null, rider_phone: body.riderPhone || null, delivery_note: body.deliveryNote || null, tracking_url: body.trackingUrl || null });
  const { error } = await admin.db.from('orders').update(update).eq('id', id); if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  await admin.db.from('order_status_history').insert({ order_id: id, from_status: order.status, to_status: body.status, note: body.note || null, changed_by: admin.userId });
  if (body.status === 'dispatched') { const text = `Your ChupaHub order #${order.order_number} has been dispatched and is on its way. Order total: KES ${Number(order.total).toLocaleString('en-KE')}. Rider: ${body.riderName || 'ChupaHub rider'}. Contact: ${body.riderPhone || 'Contact ChupaHub'}. Thank you for shopping with ChupaHub.`; if (order.customer_email) { const delivery = await sendDispatchEmail(order.customer_email, text); await admin.db.from('order_notifications').upsert({ order_id: id, channel: 'email', recipient: order.customer_email, event_key: 'dispatched', status: delivery.status, provider_reference: delivery.reference || null, error_message: delivery.error || null, attempts: 1, sent_at: delivery.status === 'sent' ? new Date().toISOString() : null }, { onConflict: 'order_id,channel,recipient,event_key', ignoreDuplicates: true }); } if (order.customer_phone) await admin.db.from('order_notifications').upsert([{ order_id: id, channel: 'sms', recipient: order.customer_phone, event_key: 'dispatched', status: 'not_configured', error_message: 'SMS provider not configured' }, { order_id: id, channel: 'whatsapp', recipient: order.customer_phone, event_key: 'dispatched', status: 'not_configured', error_message: 'WhatsApp provider not configured' }], { onConflict: 'order_id,channel,recipient,event_key', ignoreDuplicates: true }); await admin.db.from('admin_notifications').insert({ order_id: id, kind: 'dispatch', title: `Order ${order.order_number} dispatched`, body: text }); }
  return NextResponse.json({ ok: true });
}
