import type { Metadata } from 'next';
import Link from 'next/link';
import { breadcrumbSchema, JsonLd } from '@/lib/seo';
import { getSiteContent } from '@/lib/supabase';

const title = 'Contact ChupaHub Customer Care';
const description = 'Contact ChupaHub about products, alcohol delivery, payments or an existing Nairobi order.';
export const metadata: Metadata = { title, description, alternates: { canonical: '/contact' }, openGraph: { title: `${title} | ChupaHub`, description, url: '/contact', type: 'website' }, twitter: { card: 'summary', title: `${title} | ChupaHub`, description } };
export default async function ContactPage() { const content = await getSiteContent(); return <main className="mx-auto max-w-4xl px-4 py-10"><JsonLd data={[{ '@context': 'https://schema.org', '@type': 'ContactPage', name: title, description, url: 'https://chupahub.com/contact' }, breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Contact', url: '/contact' }])]}/><nav aria-label="Breadcrumb" className="mb-4 text-sm text-neutral-600"><Link href="/">Home</Link> / Contact</nav><article className="rounded-3xl bg-white p-6 shadow-card sm:p-10"><p className="font-bold uppercase tracking-wide text-brand-orange">Customer care</p><h1 className="mt-2 text-4xl font-black text-brand-ink">Contact ChupaHub</h1><div className="mt-6 grid gap-4 sm:grid-cols-2">{content.contact_phone && <a href={`tel:${content.contact_phone}`} className="rounded-2xl border border-orange-100 p-5"><span className="block text-sm font-bold text-neutral-500">Phone</span><strong className="text-brand-ink">{content.contact_phone}</strong></a>}{content.contact_email && <a href={`mailto:${content.contact_email}`} className="rounded-2xl border border-orange-100 p-5"><span className="block text-sm font-bold text-neutral-500">Email</span><strong className="break-all text-brand-ink">{content.contact_email}</strong></a>}</div>{!content.contact_phone && !content.contact_email && <p className="mt-5 text-neutral-700">Contact details will be published here by the ChupaHub team.</p>}<p className="mt-6"><Link href="/faq" className="font-black text-brand-orange">Read frequently asked questions</Link></p></article></main>; }
