import { NextRequest, NextResponse } from 'next/server';
import { kenyaPhone, requestStkPush } from '@/lib/server/mpesa';
import { getAdminSupabase } from '@/lib/server/supabase-admin';

type CartLine = { productId: string; variantId?: string; quantity: number };
const distance = (a: number, b: number, c: number, d: number) => { const r = Math.PI / 180, x = (c - a) * r, y = (d - b) * r; const h = Math.sin(x / 2) ** 2 + Math.cos(a * r) * Math.cos(c * r) * Math.sin(y / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h)); };

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as { cart: CartLine[]; customer: { name: string; email?: string; phone: string; address: string; latitude: number; longitude: number }; paymentMethod: 'mpesa'|'cash'|'pickup'; giftNote?: string };
    if (!Array.isArray(body.cart) || !body.cart.length || !body.customer?.name || !body.customer?.address || !Number.isFinite(body.customer.latitude) || !Number.isFinite(body.customer.longitude)) return NextResponse.json({ error: 'Complete your contact and delivery details before placing an order.' }, { status: 400 });
    if (!['mpesa','cash','pickup'].includes(body.paymentMethod)) return NextResponse.json({ error: 'Unsupported payment method.' }, { status: 400 });
    const db = getAdminSupabase();
    const ids = [...new Set(body.cart.map((line) => line.productId))];
    const { data: products, error: productsError } = await db.from('products').select('id,name,price,stock,product_variants(id,name,price,stock,is_active)').in('id', ids).eq('is_active', true);
    if (productsError || !products || products.length !== ids.length) throw new Error('One or more products are no longer available. Refresh your cart and try again.');
    let subtotal = 0; const items: Array<Record<string, unknown>> = [];
    for (const line of body.cart) { const product = products.find((entry) => entry.id === line.productId); const quantity = Number(line.quantity); if (!product || !Number.isInteger(quantity) || quantity < 1) throw new Error('Your cart contains an invalid quantity.'); const variant = line.variantId ? product.product_variants?.find((entry: { id: string }) => entry.id === line.variantId) : null; if (line.variantId && (!variant || !variant.is_active)) throw new Error('A selected bottle size is no longer available.'); const stock = variant ? variant.stock : product.stock, price = variant ? variant.price : product.price, name = variant ? `${product.name} — ${variant.name}` : product.name; if (stock < quantity) throw new Error(`${name} does not have enough stock available.`); subtotal += Number(price) * quantity; items.push({ product_id: product.id, variant_id: variant?.id || null, product_name: name, quantity, unit_price: price, line_total: Number(price) * quantity }); }
    const { data: checkout } = await db.from('store_settings').select('value').eq('key', 'checkout').maybeSingle(); const store = checkout?.value || {}; const { data: bands } = await db.from('delivery_settings').select('*').eq('is_active', true).order('sort_order'); const km = distance(Number(store.store_latitude ?? -1.286389), Number(store.store_longitude ?? 36.817223), body.customer.latitude, body.customer.longitude); const band = (bands || []).find((entry) => km >= Number(entry.min_distance_km) && (entry.max_distance_km == null || km <= Number(entry.max_distance_km))) || (bands || []).at(-1); if (!band && body.paymentMethod !== 'pickup') throw new Error('This delivery location is outside the configured delivery area.');
    const deliveryFee = body.paymentMethod === 'pickup' ? 0 : Number(band?.fee || 0), total = subtotal + deliveryFee, orderNumber = `CH-${Date.now().toString(36).toUpperCase()}`;
    const paymentStatus = body.paymentMethod === 'mpesa' ? 'pending_payment' : body.paymentMethod === 'cash' ? 'cash_due' : 'pending';
    const { data: order, error: orderError } = await db.from('orders').insert({ order_number: orderNumber, customer_name: body.customer.name.trim(), customer_email: body.customer.email?.trim() || null, customer_phone: body.customer.phone, delivery_address: body.customer.address.trim(), gps_lat: body.customer.latitude, gps_lng: body.customer.longitude, gift_note: body.giftNote?.trim() || null, payment_method: body.paymentMethod, payment_status: paymentStatus, status: body.paymentMethod === 'mpesa' ? 'pending_payment' : 'pending', subtotal, delivery_fee: deliveryFee, discount_total: 0, total }).select('id,order_number,checkout_token').single();
    if (orderError || !order) throw orderError || new Error('Could not create your order.');
    const { error: itemsError } = await db.from('order_items').insert(items.map((item) => ({ ...item, order_id: order.id }))); if (itemsError) throw itemsError;
    await db.from('admin_notifications').insert({ order_id: order.id, kind: 'new_order', title: `New order ${order.order_number}`, body: `${body.customer.name} placed a ${body.paymentMethod} order for KES ${total.toLocaleString('en-KE')}.` });
    if (body.paymentMethod === 'mpesa') { const phone = kenyaPhone(body.customer.phone); try { const stk = await requestStkPush({ amount: total, phone, accountReference: order.order_number, description: 'ChupaHub order' }); await db.from('payments').insert({ order_id: order.id, provider: 'mpesa', status: 'pending', amount: total, phone_number: phone, merchant_request_id: stk.merchantRequestId, checkout_request_id: stk.checkoutRequestId }); return NextResponse.json({ orderNumber: order.order_number, checkoutToken: order.checkout_token, paymentStatus: 'pending_payment', message: 'Check your phone and enter your M-Pesa PIN to complete payment.' }); } catch (error) { await db.from('orders').update({ payment_status: 'failed' }).eq('id', order.id); return NextResponse.json({ orderNumber: order.order_number, checkoutToken: order.checkout_token, paymentStatus: 'failed', error: error instanceof Error ? error.message : 'M-Pesa could not start.' }, { status: 502 }); } }
    return NextResponse.json({ orderNumber: order.order_number, checkoutToken: order.checkout_token, paymentStatus });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to place your order.' }, { status: 400 }); }
}
