'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useMemo, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { BarChart3, ChevronRight, Clock3, CreditCard, Gift, Headphones, Heart, Home, LogOut, MapPin, Package, RotateCcw, Search, Settings, Star, Truck, UserRound } from 'lucide-react';
import { createBrowserSupabase } from '@/lib/supabase-browser';
import { money } from '@/lib/supabase';
import { SignOutButton } from './SignOutButton';

type OrderItem = { id: string; product_id?: string; variant_id?: string; product_name: string; quantity: number; unit_price: number; line_total: number; products?: { name?: string; categories?: { name?: string } | null } | null };
type Order = { id: string; order_number?: string; created_at: string; total: number; discount_total?: number; delivery_fee?: number; payment_status: string; status: string; rider_name?: string; delivered_at?: string; tracking_url?: string; order_items?: OrderItem[] };
type Address = { id: string; label?: string; address: string; apartment?: string; building?: string; delivery_instructions?: string; is_default?: boolean };
type Reward = { points_balance: number; lifetime_points: number; points_redeemed: number };
type Activity = { id: string; points: number; description?: string; transaction_type: string; created_at: string };
type DashboardData = { customerId: string; name: string; email: string; phone?: string; avatar?: string; memberSince: string; orders: Order[]; addresses: Address[]; rewards: Reward; activity: Activity[] };

const tierFor = (points:number) => points >= 15000 ? ['Platinum', Infinity, 'VIP support · Early promotions · Highest priority delivery'] as const : points >= 5000 ? ['Gold', 15000, 'Free delivery vouchers · Special discounts · Priority rider dispatch'] as const : points >= 1000 ? ['Silver', 5000, 'Priority support · Exclusive offers'] as const : ['Bronze', 1000, 'Birthday coupon'] as const;
const menus = [['dashboard','Dashboard',Home],['orders','My Orders',Package],['tracking','Order Tracking',Truck],['rewards','Rewards',Gift],['addresses','Saved Addresses',MapPin],['payments','Payment Methods',CreditCard],['favourites','Favourite Drinks',Heart],['settings','Account Settings',Settings],['support','Support',Headphones]] as const;

export function AccountDashboard({ data }: { data: DashboardData }) {
  const [section,setSection]=useState<(typeof menus)[number][0]>('dashboard'),[query,setQuery]=useState(''),[message,setMessage]=useState('');
  const supabase=useMemo(()=>createBrowserSupabase(),[]),router=useRouter();
  const delivered=data.orders.filter(order=>['delivered','completed'].includes(order.status)), totalSpent=delivered.reduce((sum,order)=>sum+Number(order.total),0), saved=delivered.reduce((sum,order)=>sum+Number(order.discount_total||0),0);
  const itemCounts=new Map<string,number>(); delivered.flatMap(order=>order.order_items||[]).forEach(item=>itemCounts.set(item.product_name,(itemCounts.get(item.product_name)||0)+item.quantity));
  const favouriteDrink=[...itemCounts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Discover your next favourite';
  const categoryCounts=new Map<string,number>(); delivered.flatMap(order=>order.order_items||[]).forEach(item=>{const value=item.products?.categories?.name;if(value)categoryCounts.set(value,(categoryCounts.get(value)||0)+item.quantity)});
  const favouriteCategory=[...categoryCounts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Not enough orders yet';
  const [tier,nextTier,benefits]=tierFor(data.rewards.points_balance), remaining=Number.isFinite(nextTier)?Math.max(0,nextTier-data.rewards.points_balance):0;
  const filtered=data.orders.filter(order=>`${order.order_number} ${(order.order_items||[]).map(item=>item.product_name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const favouriteDay=delivered.length?new Intl.DateTimeFormat('en-KE',{weekday:'long'}).format(new Date(delivered[0].created_at)):'—';
  const favouriteTime=delivered.length?new Intl.DateTimeFormat('en-KE',{hour:'numeric',minute:'2-digit'}).format(new Date(delivered[0].created_at)):'—';
  const averageMonthly=delivered.length?totalSpent/Math.max(1,new Set(delivered.map(order=>order.created_at.slice(0,7))).size):0;
  function reorder(order:Order){const cart=(order.order_items||[]).filter(item=>item.product_id).map(item=>({productId:item.product_id,variantId:item.variant_id,name:item.product_name,price:Number(item.unit_price),quantity:item.quantity}));localStorage.setItem('chupahub-cart',JSON.stringify(cart));window.dispatchEvent(new Event('chupahub-cart-updated'));router.push('/checkout')}
  async function saveAddress(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;const form=new FormData(event.currentTarget),payload={customer_id:data.customerId,label:String(form.get('label')||'Home'),address:String(form.get('address')||''),building:String(form.get('building')||'')||null,apartment:String(form.get('apartment')||'')||null,delivery_instructions:String(form.get('instructions')||'')||null,is_default:data.addresses.length===0};const {error}=await supabase.from('delivery_locations').insert(payload);setMessage(error?error.message:'Address saved.');if(!error){event.currentTarget.reset();router.refresh()}}
  const OrderList=()=> <div className="space-y-4">{filtered.length?filtered.map(order=><article key={order.id} className="rounded-2xl border border-orange-100 bg-white p-4 transition hover:shadow-card"><div className="flex flex-wrap justify-between gap-3"><div><b className="text-brand-ink">{order.order_number||order.id.slice(0,8)}</b><p className="text-xs text-neutral-500">{new Date(order.created_at).toLocaleString('en-KE')}</p></div><div className="text-right"><b>{money(order.total)}</b><p className="text-xs capitalize text-neutral-500">{order.payment_status} · {order.status.replaceAll('_',' ')}</p></div></div><div className="mt-3 border-y border-orange-50 py-3 text-sm">{(order.order_items||[]).map(item=><p key={item.id}>{item.quantity} × {item.product_name}</p>)}</div><div className="mt-3 grid gap-1 text-xs text-neutral-600 sm:grid-cols-3"><span>Rider: {order.rider_name||'Assigned when dispatched'}</span><span>Delivered: {order.delivered_at?new Date(order.delivered_at).toLocaleString('en-KE'):'Not delivered'}</span><span>Total items: {(order.order_items||[]).reduce((n,item)=>n+item.quantity,0)}</span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>reorder(order)} className="inline-flex items-center gap-1 rounded-lg bg-brand-orange px-3 py-2 text-xs font-black text-white"><RotateCcw size={14}/>Order again</button><Link href={`/account/receipt/${order.id}`} className="rounded-lg border px-3 py-2 text-xs font-black">View receipt</Link>{!['delivered','completed','cancelled','refunded'].includes(order.status)&&<Link href={order.tracking_url||`/track-order?order=${encodeURIComponent(order.order_number||order.id)}`} className="rounded-lg border px-3 py-2 text-xs font-black">Track order</Link>}{order.order_items?.[0]&&<Link href={`/account/review/${order.order_items[0].id}`} className="rounded-lg border px-3 py-2 text-xs font-black">Leave a review</Link>}</div></article>):<div className="rounded-2xl border border-dashed p-8 text-center text-neutral-500">No orders match your search.</div>}</div>;
  return <main className="min-h-screen bg-[#fff8f3] px-3 py-5 sm:px-5"><div className="mx-auto max-w-7xl lg:grid lg:grid-cols-[250px_1fr] lg:gap-5"><aside className="rounded-3xl bg-brand-ink p-4 text-white lg:sticky lg:top-28 lg:h-fit"><div className="flex items-center gap-3 border-b border-white/10 pb-4">{data.avatar?<Image src={data.avatar} alt={`${data.name} profile`} width={56} height={56} unoptimized className="h-14 w-14 rounded-full object-cover"/>:<div className="grid h-14 w-14 place-items-center rounded-full bg-brand-orange"><UserRound/></div>}<div className="min-w-0"><b className="block truncate">{data.name}</b><small className="truncate text-white/60">{data.email}</small></div></div><nav aria-label="Account menu" className="mt-3 flex gap-2 overflow-x-auto lg:block">{menus.map(([key,label,Icon])=><button key={key} onClick={()=>setSection(key)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm font-bold lg:mb-1 lg:w-full ${section===key?'bg-brand-orange text-white':'text-white/75 hover:bg-white/10'}`}><Icon size={17}/>{label}</button>)}</nav><div className="mt-3 border-t border-white/10 pt-2"><SignOutButton/></div></aside><section className="mt-5 min-w-0 lg:mt-0">
    {section==='dashboard'&&<><div className="orange-gradient overflow-hidden rounded-3xl p-6 text-white shadow-orange"><p className="text-sm font-bold text-white/75">Welcome back, {data.name.split(' ')[0]} 👋</p><h1 className="mt-1 text-3xl font-black">Ready for another Chupa Hub order?</h1><p className="mt-3 text-white/90">You have completed {delivered.length} orders and have {data.rewards.points_balance.toLocaleString()} Reward Points.</p><p className="mt-1 text-sm">{remaining?`Only ${remaining.toLocaleString()} points until your next tier.`:'You have reached our highest reward tier.'}</p><button onClick={()=>setSection('orders')} className="mt-5 rounded-xl bg-white px-5 py-3 font-black text-brand-deep">View my orders</button></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{([[data.rewards.points_balance,'Reward points',Star],[money(totalSpent),'Total spent',BarChart3],[data.orders.length,'Total orders',Package],[tier,'Loyalty tier',Gift]] as Array<[string|number,string,typeof Star]>).map(([value,label,Icon])=><div key={String(label)} className="rounded-2xl bg-white p-4 shadow-sm"><Icon className="text-brand-orange" size={21}/><b className="mt-3 block text-xl text-brand-ink">{String(value)}</b><span className="text-xs text-neutral-500">{String(label)}</span></div>)}</div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Your favourites</h2><p className="mt-3 text-sm"><b>Drink:</b> {favouriteDrink}</p><p className="mt-2 text-sm"><b>Category:</b> {favouriteCategory}</p><p className="mt-2 text-sm"><b>Last order:</b> {data.orders[0]?new Date(data.orders[0].created_at).toLocaleDateString('en-KE'):'No orders yet'}</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Member profile</h2><p className="mt-3 text-sm"><b>Member since:</b> {new Date(data.memberSince).toLocaleDateString('en-KE',{month:'long',year:'numeric'})}</p><p className="mt-2 text-sm"><b>{tier} benefits:</b> {benefits}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-orange-100"><div className="h-full bg-brand-orange transition-all duration-700" style={{width:`${Number.isFinite(nextTier)?Math.min(100,data.rewards.points_balance/nextTier*100):100}%`}}/></div></div></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[[money(saved),'Money saved'],[delivered.filter(o=>Number(o.delivery_fee||0)===0).length,'Free deliveries'],[favouriteDay,'Favourite day'],[favouriteTime,'Favourite time'],[favouriteCategory,'Favourite category'],[money(averageMonthly),'Avg. monthly spend']].map(([value,label])=><div key={String(label)} className="rounded-2xl border border-orange-100 bg-white p-4"><b className="block text-brand-ink">{String(value)}</b><small className="text-neutral-500">{String(label)}</small></div>)}</div></>}
    {(section==='orders'||section==='tracking')&&<><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">{section==='tracking'?'Order tracking':'My orders'}</h1><p className="text-neutral-600">Every order linked to your customer account appears here.</p></div><label className="relative"><Search className="absolute left-3 top-3 text-neutral-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders" className="rounded-xl border bg-white py-2.5 pl-9 pr-3"/></label></div><OrderList/></>}
    {section==='rewards'&&<><h1 className="text-3xl font-black">Chupa Hub Rewards</h1><p className="mt-1 text-neutral-600">Earn 1 point for every KES 100 after an order is delivered.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[[data.rewards.points_balance,'Current balance'],[data.rewards.lifetime_points,'Lifetime earned'],[data.rewards.points_redeemed,'Points redeemed']].map(([value,label])=><div key={label} className="rounded-2xl bg-white p-5 shadow-sm"><b className="text-3xl text-brand-orange">{value}</b><p className="text-sm text-neutral-500">{label}</p></div>)}</div><div className="mt-4 rounded-2xl bg-white p-5"><h2 className="font-black">Recent points activity</h2>{data.activity.length?data.activity.map(item=><div key={item.id} className="flex justify-between border-b py-3 text-sm"><span>{item.description||item.transaction_type}<small className="block text-neutral-400">{new Date(item.created_at).toLocaleDateString('en-KE')}</small></span><b className={item.points>0?'text-green-700':'text-red-600'}>{item.points>0?'+':''}{item.points}</b></div>):<p className="mt-4 text-neutral-500">Your delivered orders will create reward activity here.</p>}</div></>}
    {section==='addresses'&&<><h1 className="text-3xl font-black">Saved addresses</h1><div className="mt-4 grid gap-3 md:grid-cols-2">{data.addresses.map(address=><div key={address.id} className="rounded-2xl bg-white p-5 shadow-sm"><b>{address.label||'Delivery address'} {address.is_default&&<span className="ml-2 rounded-full bg-orange-50 px-2 py-1 text-xs text-brand-orange">Default</span>}</b><p className="mt-2 text-sm text-neutral-600">{address.address}</p><small>{[address.building,address.apartment].filter(Boolean).join(' · ')}</small></div>)}</div><form onSubmit={saveAddress} className="mt-5 grid gap-3 rounded-2xl bg-white p-5 sm:grid-cols-2"><h2 className="font-black sm:col-span-2">Add another address</h2>{[['label','Label (Home, Work)'],['address','Street / area'],['building','Building'],['apartment','Apartment']].map(([name,label])=><label key={name} className="text-sm font-bold">{label}<input name={name} required={name==='address'} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label>)}<label className="text-sm font-bold sm:col-span-2">Delivery instructions<input name="instructions" className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><button className="orange-gradient w-fit rounded-xl px-5 py-3 font-black text-white">Save address</button>{message&&<p className="self-center text-sm font-bold">{message}</p>}</form></>}
    {section==='payments'&&<Empty title="Payment methods" text="For your security, Chupa Hub does not store card or M-Pesa credentials. Choose an available payment method securely at checkout." link="/checkout" label="Go to checkout"/>}{section==='favourites'&&<Empty title="Favourite drinks" text={`Your most ordered drink is ${favouriteDrink}. Keep ordering to make your recommendations even better.`} link="/shop" label="Explore drinks"/>}{section==='settings'&&<Empty title="Account settings" text={`Signed in as ${data.email}. Contact support to update protected customer details.`} link="/contact" label="Contact support"/>}{section==='support'&&<Empty title="Customer support" text="Need help with an order, reward points or delivery? Chupa Hub customer care is ready to assist." link="/contact" label="Get support"/>}
  </section></div></main>;
}
function Empty({title,text,link,label}:{title:string;text:string;link:string;label:string}){return <div className="rounded-3xl bg-white p-8 text-center shadow-sm"><Clock3 className="mx-auto text-brand-orange" size={40}/><h1 className="mt-3 text-3xl font-black">{title}</h1><p className="mx-auto mt-3 max-w-lg text-neutral-600">{text}</p><Link href={link} className="mt-6 inline-flex items-center gap-1 font-black text-brand-orange">{label}<ChevronRight size={17}/></Link></div>}
