'use client';

import Link from 'next/link';
import { CheckCircle2, ShoppingBag, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { type CartAddedDetail } from '@/lib/cart';
import { money } from '@/lib/supabase';

export function CartFeedback() {
  const [detail, setDetail] = useState<CartAddedDetail | null>(null), [visible, setVisible] = useState(false);
  const closeTimer = useRef<number | null>(null);
  useEffect(() => { const added = (event: Event) => { if (!(event instanceof CustomEvent) || !event.detail?.item) return; setDetail(event.detail as CartAddedDetail); setVisible(true); if (closeTimer.current) window.clearTimeout(closeTimer.current); closeTimer.current = window.setTimeout(() => setVisible(false), 5000); const cart = document.querySelector('[data-cart-icon]'); cart?.classList.remove('cart-pulse'); requestAnimationFrame(() => cart?.classList.add('cart-pulse')); }; window.addEventListener('chupahub-cart-updated', added); return () => { window.removeEventListener('chupahub-cart-updated', added); if (closeTimer.current) window.clearTimeout(closeTimer.current); }; }, []);
  if (!detail) return null;
  const count = detail.items.reduce((total, item) => total + item.quantity, 0), subtotal = detail.items.reduce((total, item) => total + item.price * item.quantity, 0);
  return <aside role="status" aria-live="polite" className={`fixed inset-x-3 bottom-3 z-[70] rounded-2xl border border-orange-100 bg-white p-4 shadow-2xl transition duration-300 sm:inset-x-auto sm:bottom-auto sm:right-5 sm:top-24 sm:w-[25rem] ${visible ? 'translate-y-0 opacity-100 sm:translate-x-0' : 'pointer-events-none translate-y-6 opacity-0 sm:translate-x-8 sm:translate-y-0'}`}><button type="button" onClick={() => setVisible(false)} aria-label="Close cart notification" className="absolute right-3 top-3 rounded-full p-1 text-neutral-500 hover:bg-neutral-100"><X size={18}/></button><div className="flex items-center gap-2 text-green-700"><CheckCircle2 size={22}/><h2 className="font-black">Added to Cart</h2></div><div className="mt-3 flex gap-3"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-white p-2 ring-1 ring-orange-100">{detail.item.image ? <img src={detail.item.image} alt="" className="h-full w-full object-contain"/> : <ShoppingBag className="text-brand-orange"/>}</div><div className="min-w-0 flex-1"><p className="truncate font-black text-brand-ink">{detail.item.name}{detail.item.size ? ` — ${detail.item.size}` : ''}</p><p className="mt-1 text-sm text-neutral-600">Successfully added to your cart.</p><p className="mt-1 text-sm font-bold">Quantity added: {detail.quantityAdded} · {money(detail.item.price)}</p></div></div><div className="mt-3 rounded-xl bg-brand-soft p-3 text-sm"><div className="flex justify-between"><span>{count} item{count === 1 ? '' : 's'} in cart</span><b>{money(subtotal)}</b></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => setVisible(false)} className="rounded-xl border-2 border-brand-orange px-3 py-2.5 text-sm font-black text-brand-orange">Continue Shopping</button><Link href="/checkout" onClick={() => setVisible(false)} className="rounded-xl border-2 border-brand-orange px-3 py-2.5 text-center text-sm font-black text-brand-orange">View Cart</Link><Link href="/checkout" onClick={() => setVisible(false)} className="orange-gradient col-span-2 rounded-xl px-3 py-2.5 text-center text-sm font-black text-white">Checkout</Link></div></aside>;
}
