'use client';

import { importLibrary, setOptions } from '@googlemaps/js-api-loader';
import { CheckCircle2, LocateFixed, Search } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { GoogleLocationMap } from './GoogleLocationMap';

export type DeliveryLocation = { latitude: number; longitude: number; placeId?: string; placeName?: string; verified: boolean };

export function LocationPicker({ address, onAddress, value, onChange }: { address: string; onAddress: (value: string) => void; value: DeliveryLocation | null; onChange: (value: DeliveryLocation | null) => void }) {
  const input = useRef<HTMLInputElement>(null), autocomplete = useRef<google.maps.places.Autocomplete | null>(null);
  const [ready, setReady] = useState(false), [error, setError] = useState(''), [locating, setLocating] = useState(false);
  useEffect(() => { const key = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY; if (!key) { setError('Google Maps is temporarily unavailable. Enter the address manually; the order will be marked Location not verified.'); return; } let active = true; setOptions({ key, v: 'weekly' }); void Promise.all([importLibrary('places'), importLibrary('maps'), importLibrary('marker')]).then(() => { if (!active || !input.current) return; autocomplete.current = new google.maps.places.Autocomplete(input.current, { componentRestrictions: { country: 'ke' }, fields: ['place_id','name','formatted_address','geometry'] }); autocomplete.current.addListener('place_changed', () => { const place = autocomplete.current?.getPlace(), point = place?.geometry?.location; if (!place?.place_id || !point) { onChange(null); setError('Please select your delivery location from the Google Maps suggestions.'); return; } const formatted = place.formatted_address || place.name || ''; onAddress(formatted); onChange({ latitude: point.lat(), longitude: point.lng(), placeId: place.place_id, placeName: place.name, verified: true }); setError(''); localStorage.setItem('chupahub-delivery-label', place.name || formatted.split(',')[0]); window.dispatchEvent(new Event('chupahub-location-updated')); }); setReady(true); }).catch(() => setError('Google Maps is temporarily unavailable. Enter the address manually; the order will be marked Location not verified.')); return () => { active = false; if (autocomplete.current) google.maps.event.clearInstanceListeners(autocomplete.current); }; }, [onAddress, onChange]);
  function changed(text: string) { onAddress(text); if (value) onChange(null); }
  function currentLocation() { if (!navigator.geolocation) { setError('Location is not supported by this browser.'); return; } setLocating(true); navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const { Geocoder } = await importLibrary('geocoding'); const result = await new Geocoder().geocode({ location: { lat: coords.latitude, lng: coords.longitude } }); const place = result.results[0]; if (!place) throw new Error(); onAddress(place.formatted_address); onChange({ latitude: coords.latitude, longitude: coords.longitude, placeId: place.place_id, placeName: place.address_components[0]?.long_name, verified: true }); setError(''); } catch { onChange({ latitude: coords.latitude, longitude: coords.longitude, verified: false }); setError('We found your coordinates but could not verify the Google address. Enter delivery details manually.'); } finally { setLocating(false); } }, () => { setError('Location permission was not granted. Search for your delivery location instead.'); setLocating(false); }, { enableHighAccuracy: true, timeout: 10000 }); }
  return <div><label className="block font-black">Search your delivery location<div className="relative mt-2"><Search className="absolute left-3 top-3 text-brand-orange" size={18}/><input ref={input} value={address} onChange={(event) => changed(event.target.value)} className="w-full rounded-xl border border-orange-200 py-3 pl-10 pr-3 font-normal" placeholder="Building, estate, road, business or landmark" autoComplete="off"/></div></label><button type="button" onClick={currentLocation} disabled={locating || !ready} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-orange-200 px-4 py-2 text-sm font-bold disabled:opacity-50"><LocateFixed size={17}/>{locating ? 'Finding address…' : 'Use my current location'}</button>{value?.verified && <p className="mt-3 inline-flex items-center gap-2 rounded-lg bg-green-50 px-3 py-2 text-sm font-bold text-green-700"><CheckCircle2 size={17}/> Location confirmed</p>}{error && <p className="mt-3 text-sm font-bold text-red-600">{error}</p>}{value && <GoogleLocationMap location={value}/>}</div>;
}
