import type { Metadata } from 'next';
import Link from 'next/link';
import { ProductCard, ProductVariantCard } from '@/components/Site';
import { absoluteUrl, breadcrumbSchema, JsonLd } from '@/lib/seo';
import { getProducts } from '@/lib/supabase';

const title='Search Chupa Hub Products';
const description='Search Chupa Hub for wine, whisky, beer, gin, vodka, champagne, spirits, mixers and drinks available in Nairobi.';
export const metadata:Metadata={title,description,alternates:{canonical:'/search'},openGraph:{title:`${title} | Chupa Hub`,description,url:'/search',type:'website'},twitter:{card:'summary',title:`${title} | Chupa Hub`,description}};
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){const {q=''}=await searchParams,query=q.trim().toLowerCase(),products=await getProducts(),results=query.length<2?[]:products.filter(product=>`${product.name} ${product.brands?.name||''} ${product.categories?.name||''} ${product.description||''}`.toLowerCase().includes(query));return <main className="mx-auto max-w-7xl px-4 py-8"><JsonLd data={[{'@context':'https://schema.org','@type':'SearchResultsPage',name:q?`Search results for ${q}`:title,url:absoluteUrl(q?`/search?q=${encodeURIComponent(q)}`:'/search'),mainEntity:{'@type':'ItemList',numberOfItems:results.length,itemListElement:results.map((product,index)=>({'@type':'ListItem',position:index+1,url:absoluteUrl(`/product/${product.slug}`),name:product.name}))}},breadcrumbSchema([{name:'Home',url:'/'},{name:'Search',url:'/search'}])]}/><nav aria-label="Breadcrumb" className="mb-4 text-sm text-neutral-600"><Link href="/">Home</Link> / Search</nav><section className="rounded-3xl bg-white p-6 shadow-card"><h1 className="text-4xl font-black text-brand-ink">Search Chupa Hub</h1><form action="/search" className="mt-5 flex gap-2"><input name="q" defaultValue={q} minLength={2} required aria-label="Search products" className="min-w-0 flex-1 rounded-xl border border-orange-200 p-3" placeholder="Search products, brands and categories"/><button className="orange-gradient rounded-xl px-5 font-black text-white">Search</button></form></section>{query.length>=2?(results.length?<section aria-label="Search results" className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5 xl:grid-cols-6">{results.flatMap(product=>{const variants=(product.product_variants||[]).filter(variant=>variant.is_active!==false);return [<ProductCard key={product.id} p={product}/>,...variants.slice(1).map(variant=><ProductVariantCard key={variant.id} product={product} variant={variant}/>)]})}</section>:<p className="mt-6 rounded-2xl bg-white p-6">No matching products found. Try a category or brand name.</p>):<p className="mt-6 text-neutral-600">Enter at least two characters to search the catalogue.</p>}</main>}
